name: hw-ip
version: '0.4.2'
synopsis: Library for manipulating IP addresses and CIDR blocks
description: Please see README.md
category: Network
author:
  - John Ky
  - David Turnbull
  - Jian Wan
maintainer: newhoggy@gmail.com
copyright: 2018 John Ky
license: BSD3
github: haskell-works/hw-ip

extra-source-files:
- README.md

dependencies:
  - appar >= 0.1.7
  - attoparsec
  - bytestring
  - containers
  - deepseq
  - generic-lens
  - hw-bits
  - iproute
  - stringsearch
  - text

library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5

executables:
  hw-ip:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -O2
      - -msse4.2
    dependencies:
    - base
    - hw-ip

tests:
  hw-ip-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hedgehog
    - hw-hspec-hedgehog
    - hw-ip
    - hspec

  hw-ip-space:
    main:               Space.hs
    source-dirs:        weigh
    dependencies:
      - base
      - hw-ip
      - weigh                 >= 0.0.6      && < 0.1
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover
