name: hw-ip
version: '0.3.0'
synopsis: Library for manipulating IP addresses and CIDR blocks
description: Please see README.md
category: Network
author: John
maintainer: newhoggy@gmail.com
copyright: 2018 John Ky
license: BSD3
github: haskell-works/hw-ip

extra-source-files:
- README.md

dependencies:
  - attoparsec
  - generic-lens
  - hw-bits
  - text

library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5

tests:
  hw-ip-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hedgehog
    - hw-hspec-hedgehog
    - hw-ip
    - hspec
