name: hw-ip
version: '0.1.0.0'
category: Network
author: John
maintainer: newhoggy@gmail.com
copyright: 2017 John Ky
license: BSD3
github: haskell-works/hw-ip
extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Network.Ip
  dependencies:
  - base >=4.7 && <5

tests:
  hw-ip-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hedgehog
    - hw-hspec-hedgehog
    - hw-ip
    - hspec
